changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - octocat
  categories:
    - title: "🚀 Features"
      labels:
        - "feature"
        - "feat"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "🧹 Maintenance"
      labels:
        - "chore"
        - "refactor"
        - "ci"
        - "test"
    - title: "📝 Documentation"
      labels:
        - "docs"
    - title: "📦 Dependencies"
      labels:
        - "dependencies"
